name: EvoFusion
favicon: null
layout_spectrum: 0.49285
typography_spectrum: 0.220481
title: A totally unique and different take on a Ford Fusion
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#D8D8C0'
    - '#26565E'
    - '#788890'
    - '#48A0B0'
    - '#000000'
  brandStrength: 0.576858
  lightness: 0.636632
  saturation: 0.979462
  rhythmicContrast: 0.761392
purpose:
  - name: null
    item: null
    url: null
