name: EvoFusion
favicon: null
layout_spectrum: 0.99326
typography_spectrum: 0.26879
title: A totally unique and different take on a Ford Fusion
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#D8D8C0'
    - '#26565E'
    - '#788890'
    - '#48A0B0'
    - '#000000'
  brandStrength: 1
  lightness: 0.375
  saturation: 0
  rhythmicContrast: 1
purpose:
  - name: null
    item: null
    url: null
