name: EvoFusion
favicon: null
layout_spectrum: 0
typography_spectrum: 0.38564
title: A totally unique and different take on a Ford Fusion
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080a09'
    - '#9cbbd7'
    - '#004976'
    - '#5d2240'
    - '#b75c95'
  brandStrength: 1
  lightness: 0.375
  saturation: 0
  rhythmicContrast: 1
purpose:
  - name: null
    item: null
    url: null
